server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: bitcoin_debug
    static_configs:
      - targets:
          - localhost
        labels:
          job: bitcoin
          node: mynode
          __path__: /var/log/bitcoin/debug.log

    pipeline_stages:
      - regex:
          expression: 'block=(?P<block_hash>[a-f0-9]+) height=(?P<height>\d+) winner=(?P<winner>[^ ]+)'
      - labels:
          block_hash:
          height:
          winner:
